### ISSUE TITLE
I can't open the react-simple-state-lab, I get "...lessons/ios_lesson.rb:6 ... undefined method ... for false:FalseClass"

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co/learn-open#30]
I can't open the [react-simple-state-lab](https://learn.co/tracks/full-stack-web-development-v6/react-redux/props/simple-state-lab).

`learn open react-simple-state-lab` gives an error
=> lib/learn_open/lessons/ios_lesson.rb:6 ... undefined method ... for false:FalseClass
I get the same error with ruby 2.3.7 and in the learn ide.
It works fine in other labs.
Manually cloning and installing the lab works just fine .

```
arye@LAPTOP-8UERGPF7:/mnt/c/Users/aryed/Desktop/vm-share/labs/react-initial-state-lab-v-000$ learn open react-simple-state-lab
Looking for lesson...Traceback (most recent call last):
        11: from /home/arye/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
        10: from /home/arye/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
         9: from /home/arye/.rvm/gems/ruby-2.5.3/bin/learn-open:23:in `<main>'
         8: from /home/arye/.rvm/gems/ruby-2.5.3/bin/learn-open:23:in `load'
         7: from /home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/bin/learn-open:7:in `<top (required)>'
         6: from /home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/lib/learn_open/opener.rb:11:in `run'
         5: from /home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/lib/learn_open/opener.rb:36:in `run'
         4: from /home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:19:in `classify'
         3: from /home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:19:in `find'
         2: from /home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:19:in `each'
         1: from /home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:20:in `block in classify'
/home/arye/.rvm/gems/ruby-2.5.3/gems/learn-open-1.2.22/lib/learn_open/lessons/ios_lesson.rb:6:in `detect': undefined method `any?' for false:FalseClass (NoMethodError)
```

**Comment by arye-eidelman** [comment]
If you run into the same issue, git clone the lab and add the .learn file from another lab in the same section.

**Comment by rudyNK** [comment]
I did what you said but is still not working for me.
